// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AddBudgetModal: typeof import('./src/components/AddBudgetModal.vue')['default']
    AddExpenseModal: typeof import('./src/components/AddExpenseModal.vue')['default']
    BudgetCard: typeof import('./src/components/BudgetCard.vue')['default']
    BudgetCardUncategorized: typeof import('./src/components/BudgetCardUncategorized.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Logo: typeof import('./src/components/Logo.vue')['default']
    ViewExpensesModal: typeof import('./src/components/ViewExpensesModal.vue')['default']
  }
}

export { }
