/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AddBudgetModal: typeof import('./src/components/AddBudgetModal.vue')['default']
    AddExpenseModal: typeof import('./src/components/AddExpenseModal.vue')['default']
    BudgetCard: typeof import('./src/components/BudgetCard.vue')['default']
    BudgetCardUncategorized: typeof import('./src/components/BudgetCardUncategorized.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    Logo: typeof import('./src/components/Logo.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ViewExpensesModal: typeof import('./src/components/ViewExpensesModal.vue')['default']
  }
}
